In [1]:
import os
os.chdir('../')

import transtab

# set random seed
transtab.random_seed(42)

/home/txl4827/miniconda3/envs/transtab/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [29]:
# load multiple datasets by passing a list of data names
allset, trainset, valset, testset, cat_cols, num_cols, bin_cols \
    = transtab.load_data(['credit-g','credit-approval'])

# build transtab classifier model
model = transtab.build_classifier(cat_cols, num_cols, bin_cols)

# specify training arguments, take validation loss for early stopping
training_arguments = {
    'num_epoch':5,
    'eval_metric':'val_loss',
    'eval_less_is_better':True,
    'output_dir':'./checkpoint'
    }

########################################

/home/txl4827/miniconda3/envs/transtab/lib/python3.9/site-packages/openml/datasets/functions.py:438: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

openml data index: 31
load data from credit-g
# data: 1000, # feat: 20, # cate: 11,  # bin: 2, # numerical: 7, pos rate: 0.70
########################################

/home/txl4827/projects/transtab/transtab/dataset.py:208: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X[bin_cols] = X[bin_cols].astype(str).applymap(lambda x: 1 if x.lower() in ['yes','true','1','t'] else 0).values
/home/txl4827/miniconda3/envs/transtab/lib/python3.9/site-packages/openml/datasets/functions.py:438: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

openml data index: 29
load data from credit-approval
# data: 690, # feat: 15, # cate: 9,  # bin: 0, # numerical: 6, pos rate: 0.56

/home/txl4827/miniconda3/envs/transtab/lib/python3.9/site-packages/torch/nn/modules/transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer was not TransformerEncoderLayer
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")

In [30]:
# cat_cols
# num_cols
# bin_cols

In [31]:
trainset[0][0]

,own_telephone,foreign_worker,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents,checking_status,credit_history,purpose,savings_status,employment,personal_status,other_parties,property_magnitude,other_payment_plans,housing,job
636,0,1,0.294118,0.061957,1.000000,0.000000,0.160714,0.000000,0.0,no checking,existing paid,radio/tv,500<=X<1000,4<=X<7,female div/dep/mar,none,car,none,own,skilled
182,0,1,0.250000,0.076868,1.000000,0.333333,0.375000,0.333333,1.0,<0,all paid,new car,no known savings,1<=X<4,male single,none,life insurance,none,own,unskilled resident
736,0,1,0.294118,0.622318,0.000000,1.000000,0.071429,0.333333,0.0,0<=X<200,existing paid,used car,<100,1<=X<4,female div/dep/mar,none,car,none,rent,high qualif/self emp/mgmt
922,0,1,0.073529,0.061406,0.666667,1.000000,0.053571,0.000000,0.0,<0,existing paid,radio/tv,<100,<1,female div/dep/mar,none,life insurance,none,rent,skilled
511,1,1,0.470588,0.244085,0.333333,0.333333,0.232143,0.000000,0.0,no checking,existing paid,used car,<100,1<=X<4,male single,none,no known property,none,for free,high qualif/self emp/mgmt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,1,1,0.250000,0.205018,0.333333,0.666667,0.285714,0.000000,0.0,0<=X<200,existing paid,furniture/equipment,no known savings,4<=X<7,male single,none,car,none,own,skilled
492,0,1,0.029412,0.054308,0.000000,0.000000,0.142857,0.333333,0.0,no checking,critical/other existing credit,radio/tv,100<=X<500,1<=X<4,female div/dep/mar,none,life insurance,none,own,skilled
849,0,1,0.117647,0.025256,1.000000,1.000000,0.678571,0.000000,0.0,<0,existing paid,radio/tv,<100,>=7,male single,none,real estate,stores,own,unskilled resident
297,0,0,0.088235,0.057060,1.000000,0.333333,0.464286,0.000000,0.0,no checking,existing paid,new car,no known savings,>=7,male single,co applicant,life insurance,none,own,unskilled resident
98,0,1,0.470588,0.114834,1.000000,1.000000,0.303571,0.000000,0.0,0<=X<200,critical/other existing credit,radio/tv,<100,>=7,male single,none,real estate,none,own,skilled

In [32]:
valset[0][0]

,own_telephone,foreign_worker,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents,checking_status,credit_history,purpose,savings_status,employment,personal_status,other_parties,property_magnitude,other_payment_plans,housing,job
32,1,1,0.205882,0.309013,0.333333,0.333333,0.196429,0.333333,0.0,0<=X<200,existing paid,new car,100<=X<500,1<=X<4,male single,none,car,none,own,skilled
924,1,1,0.294118,0.364367,0.333333,0.000000,0.642857,0.000000,0.0,<0,all paid,furniture/equipment,<100,<1,male div/sep,none,life insurance,bank,own,skilled
931,1,1,0.073529,0.078134,1.000000,0.333333,0.053571,0.000000,0.0,0<=X<200,existing paid,radio/tv,<100,<1,female div/dep/mar,none,car,none,own,skilled
796,1,1,0.205882,0.399527,0.000000,1.000000,0.571429,0.000000,1.0,<0,existing paid,used car,no known savings,>=7,male single,none,life insurance,none,for free,skilled
226,1,1,0.647059,0.589358,0.000000,0.333333,0.142857,0.333333,0.0,0<=X<200,existing paid,radio/tv,>=1000,4<=X<7,male single,co applicant,no known property,bank,own,skilled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,1,1,0.235294,0.107956,1.000000,1.000000,0.357143,0.000000,0.0,<0,existing paid,furniture/equipment,no known savings,4<=X<7,male single,none,car,none,own,skilled
768,1,1,0.117647,0.185265,0.000000,1.000000,0.160714,0.666667,0.0,0<=X<200,critical/other existing credit,furniture/equipment,<100,>=7,male single,none,car,none,rent,skilled
85,1,1,0.117647,0.063937,1.000000,0.333333,0.178571,0.333333,0.0,no checking,critical/other existing credit,business,<100,1<=X<4,female div/dep/mar,guarantor,real estate,none,own,high qualif/self emp/mgmt
527,0,1,0.000000,0.068945,0.333333,0.000000,0.410714,0.333333,1.0,no checking,critical/other existing credit,radio/tv,<100,4<=X<7,male single,none,real estate,none,own,unskilled resident
117,0,0,0.088235,0.103555,0.333333,0.666667,0.142857,0.333333,0.0,<0,critical/other existing credit,furniture/equipment,no known savings,<1,female div/dep/mar,co applicant,real estate,none,rent,skilled

In [34]:
# start training, take the validation loss on average for evaluation
transtab.train(model, trainset, valset, **training_arguments)

Epoch:  20%|████████████████████████▍                                                                                                 | 1/5 [00:01<00:05,  1.30s/it]

epoch: 0, test val_loss: 0.581228
epoch: 0, train loss: 11.3669, lr: 0.000100, spent: 1.3 secs

Epoch:  40%|████████████████████████████████████████████████▊                                                                         | 2/5 [00:02<00:03,  1.28s/it]

epoch: 1, test val_loss: 0.495891
epoch: 1, train loss: 10.4865, lr: 0.000100, spent: 2.6 secs

Epoch:  60%|█████████████████████████████████████████████████████████████████████████▏                                                | 3/5 [00:03<00:02,  1.30s/it]

epoch: 2, test val_loss: 0.480831
epoch: 2, train loss: 9.8736, lr: 0.000100, spent: 3.9 secs

Epoch:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 4/5 [00:05<00:01,  1.29s/it]

epoch: 3, test val_loss: 0.446337
epoch: 3, train loss: 9.8940, lr: 0.000100, spent: 5.2 secs

Epoch: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.33s/it]
2023-11-09 22:08:53.436 | INFO     | transtab.trainer:train:136 - load best at last from ./checkpoint
2023-11-09 22:08:53.455 | INFO     | transtab.trainer:save_model:247 - saving model checkpoint to ./checkpoint
2023-11-09 22:08:53.633 | INFO     | transtab.trainer:train:141 - training complete, cost 6.8 secs.

epoch: 4, test val_loss: 0.488648
EarlyStopping counter: 1 out of 5
epoch: 4, train loss: 9.4569, lr: 0.000100, spent: 6.6 secs

In [36]:
model.load('./checkpoint')

x_test, y_test = testset[0]

ypred = transtab.predict(model, x_test)

2023-11-09 22:09:22.330 | INFO     | transtab.modeling_transtab:load:774 - missing keys: []
2023-11-09 22:09:22.331 | INFO     | transtab.modeling_transtab:load:775 - unexpected keys: []
2023-11-09 22:09:22.333 | INFO     | transtab.modeling_transtab:load:776 - load model from ./checkpoint
2023-11-09 22:09:22.360 | INFO     | transtab.modeling_transtab:load:222 - load feature extractor from ./checkpoint/extractor/extractor.json

AttributeError: 'NoneType' object has no attribute 'iloc'

In [27]:
x_test, y_test = testset[0]

In [28]:
# make predictions on the first dataset 'credit-g'
ypred = transtab.predict(model, x_test)

AttributeError: 'NoneType' object has no attribute 'iloc'

In [21]:
# evaluate the predictions with bootstrapping estimate
transtab.evaluate(ypred, y_test, seed=123, metric='auc')

NameError: name 'ypred' is not defined